config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
  get "/search",to: "flats#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index

    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end


  def show
  end

  def edit
  end

  def create
    @flat = Flat.new(flat_params)
      if @flat.save
      redirect_to flat_path(@flat)
      else
        render 'new'
      end
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  def search
    if params[:query].blank?
      redirect_to flats_path and return
    else
      @parameter = params[:query].downcase
      @results = Flat.all.where('lower(name) LIKE :search', search: "%#{@parameter}%")
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/views/flats/_form.html.erb
<div class="container">
  <%= simple_form_for(flat) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.submit class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/flats/edit.html.erb
<h1>New Flat</h1>
<%= render "form", flat: @flat %>

app/views/flats/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    Simple AirBnB
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>

          <%= form_with url: "/search", method: :get do |form| %>
            <%= form.text_field :query, placeholder: "Search" %>
            <%= form.submit "Search", class: "btn btn-outline-success" %>
          <% end %>

          <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary" %>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>

    </div>
  </div>
</div>

<div class="container">
<div class="cards">
  <h1>All our Flats</h1>
  <br>
  <ul class="cards">
    <% @flats.each do |flat| %>
    <li><div class="card-trip">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <div class="card-trip-infos">
          <div>
            <h2><%= flat.name %></h2>
              <p><%= flat.description %></p>
              <p><i class="fa-solid fa-people-roof"></i><%= flat.number_of_guests%></p>
          </div>
            <h2 class="card-trip-pricing"><%= flat.price_per_night%>€</h2>
          </div>
          <div>
            <%= link_to "More info",flat_path(flat), class:"btn btn-link text-primary"%>
            <%= link_to "Remove",flat_path(flat), class:"btn btn-link text-danger",
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
            <%= link_to "Edit", edit_flat_path(flat), class:"btn btn-link text-warning",data: {turbo_method: :get} %>
          </div>
        </div>
    </li>
    <% end %>
  </ul>
</div>
</div>

app/views/flats/new.html.erb
<h1>New Flat</h1>
<%= render "form", flat: @flat %>

app/views/flats/search.html.erb
<h1>SEarch Results</h1>
<% @results.each do |result| %>
 <p>Appartement</p>
  <%= result.name %><br>
  <%= result.description %><br>
  <%= result.address %><br>
  <%= result.price_per_night %><br>
  <%= result.number_of_guests %><br>
<% end %>

app/views/flats/show.html.erb
<h1>Show Flat</h1>

<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2><%= @flat.name %></h2>
        <p><%= @flat.description %></p>
        <p><i class="fa-solid fa-people-roof"></i><%= @flat.number_of_guests%></p>
    </div>
      <h2 class="card-trip-pricing"><%= @flat.price_per_night%>€</h2>
  </div>
  <div>
    <%= link_to "Remove",flat_path(@flat), class:"btn btn-link text-danger",
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
    <%= link_to "Edit", edit_flat_path, class:"btn btn-link text-warning",data: {turbo_method: :get} %>
  </div>
</div>
<%= link_to "Return to all flats", flats_path, class:"btn btn-primary",data: {turbo_method: :get} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% form_tag(search_path([:flat_id]), :method => "get") do%>
    <div class= "input-group">
    <%= search_field_tag :search, params[:search], placeholder: "Type", class:"form-control" %>
    <div class="input-group-btn">
    <%= button_tag "Search", :class => "btn btn-info glyphicon glyphicon-search", :name => nil %>
    </div>
    </div>
    <%end %>
    <%= yield %>
  </body>
</html>